# linode ansible playbook

- name: nextcloud setup
  hosts: localhost
  connection: local
  gather_facts: true
  any_errors_fatal: true
  user: root
  become: yes
  vars_files:
    - group_vars/linode/vars
    - group_vars/linode/secret_vars.ymk
  roles:
    - common
    - docker
    - nextcloud
    - post
